name: 'Publish Slack notification'
description: 'Publishes Slack notification on #builds channel using credential passed in SLACK_WEBHOOK_URL env variable'

runs:
    using: "composite"
    steps:
        -
            name: "Process data"
            id: process-data
            shell: bash
            run: |
                echo "::set-output name=branch::$(echo ${{ github.ref }} | sed 's/refs\/heads\///g' | sed 's/refs\/tags\///g')"
                echo "::set-output name=sha::$(echo ${{ github.sha }} | cut -c 1-12)"

        -
            name: "Notify on Slack"
            uses: edge/simple-slack-notify@master
            if: env.SLACK_WEBHOOK_URL != null
            with:
                channel: "#builds"
                username: "GitHub Actions"
                text: |
                    *<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} | ${{ github.workflow }} #${{ github.run_number }} build on ${{ github.repository }} repository has failed for ${{ steps.process-data.outputs.branch }} branch.>*

                    _ _ _ _ _ _ _
                color: "danger"
                fields: |
                    [
                        { "title": "Repository", "value": "<https://github.com/${{ github.repository }} | ${{ github.repository }}>", "short": true },
                        { "title": "Action", "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} | ${{ github.workflow }} #${{ github.run_number }}>", "short": true },
                        { "title": "Reference", "value": "<https://github.com/${{ github.repository }}/tree/${{ steps.process-data.outputs.branch }} | ${{ steps.process-data.outputs.branch }}>", "short": true },
                        { "title": "Commit", "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }} | ${{ steps.process-data.outputs.sha }}>", "short": true },
                        { "title": "Event", "value": "${{ github.event_name }}", "short": true }
                    ]
